### ISSUE TITLE
ACTIVIDAD9_UNIDAD4_DIAGRAMA DE SECUENCIA

### ISSUE THREAD

**Issue by ang3-l32** [SistemasTecTlaxiaco/actividad-9-practica-de-diagrama-de-secuencia-equipo-xd-1#1]
[ACT9_UNIDAD4_DIAGRAMADE SECUENCIAS_FUNDSOFT.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-diagrama-de-secuencia-equipo-xd-1/files/10199118/ACT9_UNIDAD4_DIAGRAMADE.SECUENCIAS_FUNDSOFT.pdf)

**Comment by EdwinOrtiz1412** [comment]
48%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
